name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3.0.0

      - name: Install Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build && npm run pack

      - name: Cleanup Artifacts
        shell: pwsh
        run: |
          if ("${{ matrix.os }}" -eq "windows-latest") {
            npx rimraf "dist/!(*.exe)"
          } elseif ("${{ matrix.os }}" -eq "macos-latest") {
            npx rimraf "dist/!(*.dmg)"
          }

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/**"
          tag_name: ${{ steps.tag.outputs.tag }}
